language: node_js
node_js:
  - '6'
  - '8'
cache:
  directories:
    - node_modules
script:
  - npm run test-browser
  - npm run coverage
after_success: npm run docs
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  local_dir: docs/
  skip_cleanup: true
  github-token:
    secure: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
    node: '6'
