language: node_js
node_js:
  - '6'
  - '8'
script: npm run coverage
cache:
  directories:
    - node_modules
deploy:
  - provider: pages
    local_dir: docs/
    skip_cleanup: true
    target_branch: gh-pages
    github_token:
        secure: PyUEDUYGSVOoqq1Y0AC7vp+s1llhI4Rcq74VWBMtGDcr/Xmbo7aEHEq/uXFTgwGu9GDxcMV4e17evazLShy9qGowJZeflNs8DKo3lop3Z/BOyHNp9L8yUaOfJox0QikEz9OnGk2jBzSpxSYl6bsGIsoTzsrtNPn0UVSVj82CwLqYxzYmgl5lpPyeSAM5W9NbYOX74PM7xO/xosrJBAo17ar+37a4X2fZcqMoMK6JFymEt5f/mPNtMBzRlz2NolcWgFUUfsARe1TTrIMQA0MQGchFeh7tb2Q/a+BKPGi6hNISmmSXG69FlL/VrzDpyN32uziUcURHPqK3I340eGIfOGwZPrOdA+8XyTGWBmXhtfqs9iDtDOZsVfZb0GR8Bno5DL8s/2tHBP7nXBtqI5tXv+CtVt5AsK59P8yYbxU/DyJSbe9zH62BFOehRPVy3wHAQyJ88JQSaOHtbV0SRxyd47v8Niw8tB+l5pFCcndvOrWzedaDt28xrgy5u5WZC9F+Dn7pOpRDsj9R1b0gLZXN3G24DY+sjc8Q1xvT6Ru8GIMadvqfFwyqxGYtn3wymyIKuYdO8vL9VmDYCkYIZ/XtdTx3UUpmvDDyUYI/e6Hae3drudt/PPTX8IXXAQpCcJgqcmhPVLlL1DFsDTcrbXlC+Xy8uw6Nb57e/H32VajK5jk=
    on:
      branch: master